# Generated by Django 5.2.7 on 2025-11-19 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('domicilio', models.TextField()),
                ('puesto', models.CharField(max_length=50)),
                ('especialidad_mascotas', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_compañia', models.AutoField(primary_key=True, serialize=False)),
                ('compañia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('tiempo_entrega_dias', models.IntegerField(default=1)),
                ('licencia_sanitaria', models.CharField(max_length=250, unique=True)),
                ('especialidad_productos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_mascota_preferida', models.CharField(blank=True, max_length=50, null=True)),
                ('id_empleado_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mascotas.empleado')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cuidados_especiales', models.CharField(blank=True, max_length=250, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=200, null=True)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('pez', 'Pez'), ('otro', 'Otro')], max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('alimentacion_recomendada', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='app_mascotas.cliente')),
                ('id_empleado_cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_cuidadas', to='app_mascotas.empleado')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('alimento', 'Alimento'), ('juguete', 'Juguete'), ('accesorio', 'Accesorio'), ('higiene', 'Higiene y Cuidado'), ('salud', 'Salud'), ('transporte', 'Transporte')], max_length=50)),
                ('garantia_meses', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('tipo_mascota', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('pez', 'Pez'), ('universal', 'Universal')], default='universal', max_length=50)),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mascotas.proveedor')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.empleado')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_mascotas.venta')),
            ],
            options={
                'db_table': 'detalle_ventas',
            },
        ),
    ]
